version: "3.7"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.3.6.7-alpine
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "127.0.0.1:8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - clickhouse_logs:/var/log/clickhouse-server/

  superset:
    env_file: docker/.env
    image: superset:0.0.0
    container_name: superset
    restart: unless-stopped
    ports:
      - 8088:8088

volumes:
  clickhouse_data:
    external: false
  clickhouse_logs:
    external: false
